# Generated by Django 3.0.5 on 2020-05-13 01:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0002_auto_20200303_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mediciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=20, verbose_name='Fecha')),
                ('origen', models.CharField(max_length=20, verbose_name='Origen')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('codigos', models.IntegerField(verbose_name='Codigos')),
                ('observacion', models.IntegerField(verbose_name='Observacion')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
